telephony: Don't enforce tone properties
* A new type of ROM is emerging and it relies on this to be relaxed
  for portability. If a prop is not set anywhere else and is annotated
  with "?=" (prop?=value), it's treated as a normal prop (prop=value).
  These are overridden only if the said prop is set somewhere with the
  "=" notation (prop=value) at the same time after this change.

* This also fixes the following errors that are generated with this
  type of project (If they're planning to override the default tones
  with their own) without breaking the original props in the product;

```
error: found duplicate sysprop assignments:
ro.config.alarm_alert=Your_Gift_To_Me.ogg
ro.config.alarm_alert=Bright_morning.ogg
error: found duplicate sysprop assignments:
ro.config.notification_sound=Your_Gift_To_Me.ogg
ro.config.notification_sound=Eureka.ogg
error: found duplicate sysprop assignments:
ro.config.ringtone=Your_Gift_To_Me.ogg
ro.config.ringtone=Your_new_adventure.ogg
```

Signed-off-by: Stella Bloom <windowz414@gnuweeb.org>